#!/bin/bash
# Script to create and push to GitHub repository
# Author: BESLI SAUT MARITO PAKPAHAN

echo "================================================"
echo "GitHub Repository Setup"
echo "Author: BESLI SAUT MARITO PAKPAHAN"
echo "================================================"
echo ""
echo "Proyek: 4-Link Planar Robot Kinematics Simulation"
echo "Total files: 55+ (termasuk 40 output berkualitas tinggi)"
echo "Size: ~24MB"
echo ""
echo "✨ FITUR KHUSUS:"
echo "  - 5 GIF animasi yang auto-play di GitHub!"
echo "  - README dengan animasi interaktif"
echo "  - Semua file dengan author attribution"
echo ""
echo "================================================"
echo "LANGKAH-LANGKAH UPLOAD KE GITHUB:"
echo "================================================"
echo ""
echo "1. Buka browser dan login ke GitHub (https://github.com)"
echo ""
echo "2. Klik tombol '+' di pojok kanan atas, pilih 'New repository'"
echo ""
echo "3. Isi form dengan:"
echo "   - Repository name: planar-robot-kinematics"
echo "   - Description: 4-Link Planar Robot Kinematics Simulation - By BESLI SAUT MARITO PAKPAHAN"
echo "   - Public atau Private (pilih sesuai keinginan)"
echo "   - JANGAN centang 'Initialize with README' (kita sudah punya)"
echo ""
echo "4. Klik 'Create repository'"
echo ""
echo "5. Setelah repository dibuat, GitHub akan menampilkan instruksi."
echo "   Salin URL repository (contoh: https://github.com/username/planar-robot-kinematics.git)"
echo ""
echo "6. Kembali ke terminal ini dan jalankan perintah berikut:"
echo ""
echo "   git remote add origin https://github.com/USERNAME/planar-robot-kinematics.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "   (Ganti USERNAME dengan username GitHub Anda)"
echo ""
echo "================================================"
echo "ATAU, jika sudah punya GitHub CLI (gh):"
echo "================================================"
echo ""
echo "Jalankan perintah ini:"
echo ""
echo "  gh repo create planar-robot-kinematics --public --source=. --push"
echo ""
echo "================================================"
echo "STATUS CURRENT REPOSITORY:"
echo "================================================"
echo ""

# Show git status
git status

echo ""
echo "Repository lokal sudah siap untuk di-push!"
echo "Ikuti langkah di atas untuk upload ke GitHub."
echo ""
echo "KONTEN REPOSITORY:"
echo "  - README.md (dokumentasi lengkap)"
echo "  - kinematics.py (forward & inverse kinematics)"
echo "  - visualizer.py (visualisasi berkualitas tinggi)"
echo "  - 4 simulation scripts"
echo "  - interactive_demo.ipynb (Jupyter notebook)"
echo "  - 35 high-quality outputs (gambar & video)"
echo "  - requirements.txt"
echo ""
